
SELECT * FROM gender;
SELECT * FROM Gyms;
SELECT * FROM Maintenances;
SELECT * FROM Members;
SELECT * FROM membership_type;
SELECT * FROM MembershipPlans;
SELECT * FROM Memberships;
SELECT * FROM Photos;
SELECT * FROM SUPPLEMENTORDERS;
SELECT * FROM SUPPLEMENTS;
